{% set name = "HaMStR" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # path: ../
  git_url: https://github.com/BIONF/conda-recipes
  git_depth: 1

build:
  noarch: generic
  number: 1

requirements:
  build:
    # - perl
  run:
    - perl
    - perl-app-cpanminus
    - r >=3.6
    - r-biocmanager
    - r-devtools
    - bioconductor-biostrings
    - pkg-config
    - wise2
    - perl-bioperl
    - perl-bioperl-core
    - perl-bioperl-run
    - blast
    - hmmer
    - clustalw
    - mafft
    - muscle
    - fasta3

test:
  commands:
    - which setup_hamstr 2>&1

about:
  home: 'https://github.com/BIONF/HaMStR'
  license: GPLv3
  summary: "Feature-aware phylogenetic profiling tool"
