{% set name = "FAS" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/g/greedyFAS/greedyFAS-{{ version }}.tar.gz
  sha256: 5b987a26db1b89b2100ca420c4acba7514374a21c576c98f1281cedf974706c5

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - perl
    - hmmer
    - tensorflow

test:
  commands:
    - greedyFAS -h 2>&1
    - parseInterPro -h 2>&1

about:
  home: 'https://github.com/BIONF/FAS'
  license: GPL
  summary: "Tool for protein feature architecture comparisons"
